
const Map<String, String> ar = {
  "name_app": "اذان المغرب",
  "error_wrong": "حدث خطأ ما حاول مرة أخرى في وقت لاحق",
  "logout": "تسجيل خروج",
  "exit_app": "هل أنت متأكد من انك تريد الخروج؟",
  "no": "لا",
  "yes": "نعم",
  "error_connection": "لا يوجد اتصال بالإنترنت. تأكد من تشغيل Wi-Fi أو البيانات الخلوية ، ثم حاول مرة أخرى",
  "azan_settings": "اعدادات الاذان",
  "done": "تم",
  "prayer_alerts_minutes": "تنبيهات الصلاة (بالدقائق)",
  "method_calculating_prayer": "طريقه حسابة الصلاه",
  "time_pray": "حان وقت صلاة %s",
  "next_prayer": "الصلاة القادمة في غضون %s دقائق",
  "grant_access_location": "يرجى منح صلاحية الوصول الى الموقع",
  "turn_gps": "المرجو تشغيل GPS",
  "no_internet": "لا يوجد اتصال بالانترنت",
  "try_again": "اعادة المحاولة",
  "make_sure_gps_turn": "يرجى التأكد من تشغيل GPS والمحاولة مرة أخرى",
  "lung": "اللغة",
  "prayer": "صلاة %s",
  "error_calendar": "تعذر جلب البيانات. هل الجهاز متصل بالإنترنت؟",
  "error_server": "عذرً! حدث خطأ ما، حاول لاحقًا",
  "choose_city": "اختر المدينة التي تعيش فيها",
  "loading": "جاري تحميل",
  "info_app": "تم تطوير Adan Maroc من قبل  INOSER maroc اللتي تهدف إلى زيادة وعي الجمهور المنتمين إلى النظام البيئي التعليمي بالتحديات التعليمية والاجتماعية التي يواجهونها ، لأننا نعلم جميعًا أن اكتساب المعرفة اليوم يتم من خلال الإنترنت والتواصل المجتمعي.",
  "city": "المدينة",
  "select_city": "اختر مدينة",
  "not_sensors": "الجهاز لايحتوي على حساسات",
  "error_reading": "خطأ في قراءة العنوان: %s",
  "direction_qibla": "قد يتأثر الهاتف بالمعادن المحيطة !  لا تعتمد عليه إلا في حالة عدم معرفتك لاتجاه القبلة",
  "permission_denied": "تم رفض إذن خدمة الموقع",
  "retry": "أعد المحاولة",
  "enable_location": "الرجاء تمكين خدمة الموقع",
  "service_denied": "رفض خدمة الموقع إلى الأبد!",
  "allow_notify": "السماح بالإخطارات",
  "send_notify": "يود التطبيق إرسال إشعارات إليك",
  "dont_allow": "لا تسمح",
  "allow": "السماح",
  "open_settings": "Ouvrir les paramètres",
  "cancel": "Annuler",
  "msg_setting": "Please make sure to active Auto-launch, Secondary launch and Run in background\nthis app may not work properly and notifications may be delayed",
  "msg_setting2": "Please set the power usage setting to be manual\nthis app may not work properly and notifications may be delayed",
  "battery_settings":"Battery Optimization Settings"
};