
const Map<String, String> fr = {
  "name_app": "Adhan Maroc",
  "error_wrong": "Une erreur s'est produite, réessayez plus tard",
  "logout": "Logout",
  "exit_app": "Are you sure you want to Exit?",
  "no": "NO",
  "yes": "YES",
  "error_connection": "No internet connection. Make sure Wi-Fi or cellular data is turned on, then try again",
  "azan_settings": "Paramètres El Adhan",
  "done": "Terminé",
  "prayer_alerts_minutes": "Alertes de prière (minutes)",
  "method_calculating_prayer": "La méthode de calcul de la prière",
  "time_pray": "Il est temps de prier %s",
  "next_prayer": "Prochaine prière dans %s minutes",
  "grant_access_location": "Veuillez autoriser l'accès à l'emplacement",
  "turn_gps": "Veuillez activer le GPS",
  "no_internet": "Pas de connexion Internet",
  "try_again": "Réessayer",
  "make_sure_gps_turn": "Veuillez vous assurer que le GPS est activé et réessayer",
  "lung": "La langue",
  "prayer": "Prière %s",
  "error_calendar": "Impossible de récupérer les données. L'appareil est-il en ligne ?",
  "error_server": "Quelque chose a mal tourné !, réessayez plus tard",
  "choose_city": "Choisissez la ville où vous habitez",
  "loading": "chargement",
  "info_app": "Adan Maroc est développé par INOSER maroc dont le but est de sensibiliser le public appartenant à l'écosystème éducatif aux défis éducatifs et sociaux auxquels ils sont confrontés, car nous savons tous que l'acquisition des connaissances se fait aujourd'hui par Internet et la communication communautaire.",
  "city": "Villes",
  "select_city": "Sélectionnez une ville",
  "not_sensors": "L'appareil n'a pas de capteurs",
  "error_reading": "Erreur de lecture du titre: %s",
  "direction_qibla": "Le téléphone peut être affecté par le métal environnant ! Ne vous y fiez pas sauf si vous ne connaissez pas la direction de la Qibla",
  "permission_denied": "Autorisation de service de localisation refusée",
  "retry": "Réessayez",
  "enable_location": "Veuillez activer le service de localisation",
  "service_denied": "Service de localisation refusé",
  "allow_notify": "Autoriser les notifications",
  "send_notify": "L'application souhaite vous envoyer des notifications",
  "dont_allow": "Ne pas autoriser",
  "allow": "Permettre",
  "open_settings": "Ouvrir les paramètres",
  "cancel": "Annuler",
  "msg_setting": "Please make sure to active Auto-launch, Secondary launch and Run in background\nthis app may not work properly and notifications may be delayed",
  "msg_setting2": "Please set the power usage setting to be manual\nthis app may not work properly and notifications may be delayed",
  "battery_settings":"Battery Optimization Settings"

};